Полноэкранный режим внутри мультивиджета
kometa-dev/MITK pull request #36
Opened 2022-09-21 08:33 UTC by IliaF

https://kometa-viewer.atlassian.net/browse/QTVIEW-66
https://kometa-viewer.atlassian.net/browse/QTVIEW-100

2022-10-03 09:32 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkRenderWindowMenu.cpp
> +void QmitkRenderWindowMenu::OnFullScreenButton( bool /*checked*/ )
почему бы не использовать эту переменную checked вместо !m_FullScreenMode

2022-10-03 09:37 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +      renderWindowWidget->setVisible(state ? currentRenderWindow == renderWindow : true);
Лучше более мнемоничное имя, чем state, например maximized

2022-10-03 13:30 UTC, IliaF commented on Modules/QtWidgets/src/QmitkRenderWindowMenu.cpp
> +void QmitkRenderWindowMenu::OnFullScreenButton( bool /*checked*/ )
Так как QToolButton без состояния checkable.

2022-10-04 14:58 UTC, sercxjo requested changes
После закрытия всех серий и повторном открытии мультивиджеты исчезают

2022-10-13 20:47 UTC, sercxjo commented
Странное поведение программы после повторной загрузки (видео в тикете.
1. После смены режима на МПР, закрытия и открытия заново перекрестие остаётся до завершения открытия.
2. После определённых переключений режимов и повторного открытия иногда путает основной вид (см. видео блитже к концу).
3. В конце всех манипуляций буквы в названии плоскости не умещаются, возможне это связано с предыдущими изменениями.
4. Если включить режим 2D слева 3D справа и потом стандартный, почему-то активизируется линейка.

2022-10-14 07:59 UTC, sercxjo approved these changes

2022-10-14 07:59 UTC, sercxjo commented
Замеченные баги были связаны с предыдущими слияниями

2022-10-15 08:40 UTC, merged