Overlay qt and active
kometa-dev/MITK pull request #40
Opened 2022-09-23 09:14 UTC by zapok

Добавлен новый оверлейный слой с активными элементами. Создание интерфейса изменено на qt.
Активный оверлейный слой подсвечивается синим цветом. При нажатии становится редактируемым (мигает курсор). После изменения значения, надо или нажать Enter или на какую-то область экрана.
Добавлена надпись с проекцией с редактиремым цветом.
Так же в рамках задачи было сделано обновление масштаба и wl на оверлейном слое при изменении значений и добавлена отрисовка линейки.

2022-09-23 11:11 UTC, zapok commented
http://195.210.170.210:8000/Viewer-win64-2022-09-23_qt_overlay_and_ruler.zip

2022-09-24 09:16 UTC, zapok commented
http://195.210.170.210:8000/Viewer-win64-2022-09-23_qt_layout_and_ruler_2.zip

2022-09-28 08:58 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +          lineCountInCorner[corner] ++;
Убрать пробел

2022-09-28 08:59 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +          lineCountInCorner[corner] ++;
Убрать пробел

2022-09-28 09:00 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +        int fontHeight = renderWindow->height() / 5.0 / maxCount;
Значение 5.0 вынести в константу.

2022-09-28 14:40 UTC, IliaF requested changes

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +      QWidget* overlayWidget = m_overlayWidgets[renderWindow];
QWidget* overlayWidget = m_overlayWidgets[renderWindow];
перенести в конструкцию:
 if (event->type() == QEvent::Resize) { }

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +          emit setActiveMode (mode);
emit setActiveMode (mode); -> emit setActiveMode(mode);
убрать пробел здесь и в подобных случаях.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +  for (uint32_t i = 0; i < m_renderWindows.size(); i++)
for {
}

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +      }else {
} else {

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +      if (std::string::npos != it)
if () {
}

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +    auto ruler = drawRuler (baseRenderer, image, true);
auto ruler = drawRuler (baseRenderer, image, true); -> auto ruler = drawRuler(baseRenderer, image, true);
Убрать пробел здесь и в подобных случаях.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +    switch (i)
switch (i) {

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +  if(renderSize[0] > 100 && renderSize[1] > 100) {
Значение 100 вынести в константу.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +        int screenReminder =  abs(remainder(lengthInMM, 10.0f) / screenOnePixelInWorld);
Отступ по код-стайлу сделать здесь и далее.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +  QString transparentStyle = QString(
Вынести в .qss файл и назначить для QLineEdit и QLabel имя объектов, чтобы специализировать стили.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +}
Добавить конец файла.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    std::vector<vtkRenderer *> m_ren;
m_cornerText, m_textProp, m_ren нигде не используются.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    TRenderWindows m_renderWindows;
Привести к код-стайлу все переменные-члены.
Пример: m_renderWindows -> m_RenderWindows.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    bool isWl(vtkCornerAnnotation::TextPosition corner, int i);
Переименовать функции на информативные: isImagePosition() и isWindowLevel().

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  }
Удалить данный кусок кода, так как renders в дальнейшем не используется.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  }
Удалить данный кусок кода, так как renders дальше нигде не используется.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    QMap <int, QMap <QPair<vtkCornerAnnotation::TextPosition, int>, QWidget*>> m_TextLinesForRenderWindow;
Привести к код-стайлу:
QMap<int, QMap<QPair<vtkCornerAnnotation::TextPosition, int>, QWidget*>>.
Почему в качестве ключа используется индекс, а не QmitkRenderWindow*? Использование указателя на окно ускорит получение целевого значения в updateOverlayForRender().

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    int m_maxLinesCount = 12;
Если в дальнейшем  не планируется менять данное поле, то вынести в константу.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    bool m_cornerAnnotationVisible = true;
Код-стайл: m_CornerAnnotationVisible.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/include/QmitkStdMultiWidget.h
> +  AnnotationOverlay m_annotationOverlay;
Код-стайл: m_AnnotationOverlay.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +  return corner == vtkCornerAnnotation::LowerLeft && i == m_maxLinesCount - (4 - 2);
В комментариях описать логику расчета индекса.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +          }
Я бы вынес в отдельные функции:
 - обновление позиции updateImagePosition();
 - обновление масштаба updateScale();
 - обновление уровня окна updateImageWindowLevel();
для облегчения поддержки в дальнейшем.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +          if (intTextValue != 0) {
Не должна ли здесь быть проверка intTextValue > 0 ?

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +          if (topNode.IsNull())
Код-стайл: if () {
Не хватает проверки, что список nodes не пуст.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +    int y;
Проинициализировать переменные.

2022-09-28 14:40 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +  QGridLayout* m_LinesLayout = new QGridLayout ();
m_LinesLayout локальная переменная, поэтому linesLayout.

2022-09-28 14:41 UTC, IliaF commented
Необходимо сначала влить изменения из PR: https://github.com/kometa-dev/MITK/pull/41 и перебазировать данный PR.

2022-09-29 12:03 UTC, sercxjo requested changes
Ещё надо убрать старые теперь неиспользуемые хедеры и переменные.
Но непонятно зачем нужно было создавать новый клвсс AnnotationOverlay и переносить в него функции из QmitkRenderWindowWidget

2022-09-29 12:03 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  }
вектор создаётся и заполняется, но дальше не используется, зачем?

2022-09-29 12:03 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  return;
почему так?

2022-09-29 12:03 UTC, sercxjo commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    std::vector<vtkCornerAnnotation *> m_cornerText;
неиспользуемые поля

2022-09-29 12:03 UTC, sercxjo commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    std::vector<vtkRenderer *> m_ren;
заполняется, но не используется

2022-09-29 12:03 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +
убрать пробелы в коце строки здесь и далее

2022-09-29 12:03 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +      //m_relationships.push_back(relationships[i]);
убрать или прокомментировать

2022-09-29 12:55 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +  QString qtText = Utilities::convertFromLocalEncoding(text);
у нас во всех тэгах  utf8, кодировка неверная!

2022-10-07 12:29 UTC, zapok commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    std::vector<vtkRenderer *> m_ren;
m_cornerText, m_textProp удалил. 
m_ren используется при инициализации и в deinitialize

2022-10-07 12:53 UTC, zapok commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    QMap <int, QMap <QPair<vtkCornerAnnotation::TextPosition, int>, QWidget*>> m_TextLinesForRenderWindow;
Рефакторинг сделал. 
в updateOverlayForRender прироста производительности не будет т.к. еще выполняется кода в разы больше по ресурсоемкости.
А в setCornerAnnotation мы имеем только индекс (номер окна). И получение по нему QmitkRenderWindow как усложнит код, так и потребует дополнительных операций.

2022-10-07 12:57 UTC, zapok commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  }
удалил

2022-10-07 12:57 UTC, zapok commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  return;
убрал return

2022-10-07 12:59 UTC, zapok commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +  QString qtText = Utilities::convertFromLocalEncoding(text);
Исправил на utf8

2022-10-07 13:00 UTC, zapok commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +          if (intTextValue != 0) {
Исправил

2022-10-07 13:01 UTC, zapok commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +      QWidget* overlayWidget = m_overlayWidgets[renderWindow];
Исправил

2022-10-08 21:14 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  return;
не убрал

2022-10-09 07:01 UTC, zapok commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +    std::vector<vtkRenderer *> m_ren;
m_ren тоже убран

2022-10-10 11:45 UTC, merged