QTVIEW-51 Changed QmitkRenderWindow to opengl rendering
kometa-dev/MITK pull request #41
Opened 2022-09-23 10:20 UTC by zapok

QmitkRenderWindow теперь вместо QVTKWidget наследует QVTKOpenGLNativeWidget (для возможности отрисовки графических элементов qt с прозрачным фоном поверх изображения окна).

2022-09-23 10:21 UTC, zapok commented
http://195.210.170.210:8000/Viewer-win64-2022-09-16_opegl_render_widget.zip

2022-09-25 10:05 UTC, IliaF requested changes

2022-09-25 10:05 UTC, IliaF commented on Modules/Core/src/Rendering/mitkRenderWindowBase.cpp
> +  auto renderingManager = mitk::RenderingManager::GetInstance();
Инициализацию перенести в строчку 73, где используется renderingManager.

2022-09-25 10:05 UTC, IliaF commented on Modules/Core/src/Rendering/mitkRenderWindowBase.cpp
> +  if ((this->GetVtkRenderWindow()->GetSize()[0] > 10) && (this->GetVtkRenderWindow()->GetSize()[1] > 10))
Блок if обозначит фигурными скобками { }.
Убрать скобки внутри условия (по приоритету операций: операторы сравнений выполняться раньше логического и).
Вынести константное значение 10 в отдельную константу, либо прокомментировать это значение.

2022-09-26 14:19 UTC, sercxjo requested changes

2022-09-26 14:19 UTC, sercxjo commented on Modules/QtWidgets/include/QmitkRenderWindow.h
>  #include "mitkInteractionEventConst.h"
#include "QVTKWidget.h" убрать, раз уж мы переходим на другой виджет

2022-09-26 14:19 UTC, sercxjo commented on Modules/QtWidgets/include/QmitkRenderWindow.h
> +#include <QVTKOpenGLNativeWidget.h>
Перенести на место include QVTKWidget.h, соблюдая группировку по библиотекам

2022-10-02 21:48 UTC, sercxjo requested changes

2022-10-02 21:48 UTC, sercxjo commented on Modules/QtWidgets/include/QmitkRenderWindow.h
> +
Лишнюю пустую строку тоже убери

2022-10-02 21:48 UTC, sercxjo commented on Modules/Core/src/Rendering/mitkRenderWindowBase.cpp
> +    m_Renderer->InitSize(this->GetVtkRenderWindow()->GetSize()[0], this->GetVtkRenderWindow()->GetSize()[1]);
здесь тело if в фигурные скобки

2022-10-06 16:10 UTC, sercxjo approved these changes

2022-10-06 16:13 UTC, IliaF approved these changes

2022-10-06 16:45 UTC, merged