Overlay set2
kometa-dev/MITK pull request #50
Opened 2022-11-16 07:51 UTC by zapok

Добавлено:
Исправлена проблема с отрисовкой активных элементов, когда число символов в них увеличивается.
Убран QLabel - теперь только QLineEdit
Добавлено редактирование V, T и ширина среза через активный оверлейный слой.
Заполнение оверлейного слоя изменено на построчное (передача текста для каждой строки отдельно).
Исправлена проблема с обновлением линейки во время перемещения мышкой изображения
Изменен способ определения вида активного элемента - раньше по номеру строки было, теперь через property QObject
Добавлено изменение активный элемент T для вида 3d. Так же добавлена надпись в нижнем левом углу (3D).
Изменен синий цвет оверлейного слоя на желтый.

Задачи:
https://kometa-viewer.atlassian.net/browse/QTVIEW-129
https://kometa-viewer.atlassian.net/browse/QTVIEW-130
https://kometa-viewer.atlassian.net/browse/QTVIEW-154
https://kometa-viewer.atlassian.net/browse/QTVIEW-161
https://kometa-viewer.atlassian.net/browse/QTVIEW-162
https://kometa-viewer.atlassian.net/browse/QTVIEW-165
https://kometa-viewer.atlassian.net/browse/KV2021-768

Сборка:

http://195.210.170.210:8000/Qt2/vlad/Viewer-win64-2022-11-15_overlay_set2.zip

2022-11-22 12:47 UTC, IliaF requested changes

2022-11-22 12:47 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +        if (intTextValue > 0)
Code style

2022-11-22 12:47 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +void AnnotationOverlay::setLineText(unsigned int i, vtkCornerAnnotation::TextPosition corner, unsigned int lineNumber, const std::string& text, ActiveOverlayType activeType)
setLineText() неоднозначное поведение: функция и устанавливать текст, и добавляет/удаляет редактируемость и переназначает тип QLineEdit, хотя по названию должна только устанавливать текст.

2022-11-22 12:47 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +  connect(line, &QLineEdit::editingFinished, [this, line, handledWidget]() {
Сonnect должен добавляться только к редактируемым QLineEdit.
Установка/удаление возможности редактировать необходимо делать через setReadOnly(state).

2022-11-24 16:45 UTC, zapok commented
http://195.210.170.210:8000/Qt2/vlad/Viewer-win64-2022-11-24_overlay_set2.zip

2022-11-30 12:58 UTC, sercxjo requested changes

2022-11-30 12:58 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +      for (int l=0; l < MAX_LINES_COUNT; i++) {
Ошибка! инкрементируется не та переменная!

2022-11-30 12:58 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +        "color: white;"
Перенести постоянную часть этих стилей в Plugins/org.blueberry.ui.qt/resources/darkstyle.qss и Plugins/org.blueberry.ui.qt/resources/lightstyle.qss

2022-11-30 12:58 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +          updateThickslices(handledWidget, intTextValue);
Установка толщины не всегда срабатывает (то меняется то нет), устанавливаемая толщина среза не соответствует дейстивельности, 1 это на самом деле 3, 2 это 5 и т.д., таким образом, отключить толстый срез невозможно.

2022-12-01 10:11 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +      for (int l=0; l < MAX_LINES_COUNT; i++) {
поправил

2022-12-14 20:59 UTC, zapok commented
195.210.170.210:8000/Qt2/vlad/Viewer-win64-2022-12-14_overlay_set.zip

2022-12-15 15:53 UTC, sercxjo requested changes

2022-12-15 15:53 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +                            "background: transparent;";
Эта общая часть тоже должна быть в общем qss

2022-12-15 15:53 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +  baseRenderer->RequestUpdate();
Где-то тут при изменении позиции по времени сбрасывается масштаб

2022-12-16 09:45 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  mitk::BaseRenderer::GetInstance(mitkWidget->renderWindow())->GetCameraController()->moveEvent.AddListener(mitk::MessageDelegate<QmitkStdMultiWidget>(this, &QmitkStdMultiWidget::updateOverlay));
зачем повтор?

2022-12-16 12:12 UTC, zapok commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  mitk::BaseRenderer::GetInstance(mitkWidget->renderWindow())->GetCameraController()->moveEvent.AddListener(mitk::MessageDelegate<QmitkStdMultiWidget>(this, &QmitkStdMultiWidget::updateOverlay));
Не повтор. В строчке есть различие: zoomEvent и moveEvent

2022-12-16 17:17 UTC, zapok commented
http://195.210.170.210:8000/Qt2/vlad/Viewer-win64-2022-12-16_overlay_set2.zip

2022-12-20 08:33 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
>        if (doIncrement) {
Заменить на условие (lineEdit->text().trimmed() != "") и переменную doIncrement удалить.

2022-12-20 08:38 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +    if (m_RenderWindows[i]->isWindow3d()) {
Заменить m_RenderWindows[i] на m_RenderWindows.at(i), чтобы исключить создание нового окна.

2022-12-20 08:42 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +        countLines++;
Переменная countLines инкрементируется, но нигде не используется.

2022-12-20 08:44 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +      auto direction = getDirectionAsText(m_RenderWindows[i]->GetSliceNavigationController()->GetViewDirection(), true).toUtf8().constData();
Заменить m_RenderWindows[i] на m_RenderWindows.at(i), чтобы исключить создание нового окна.

2022-12-20 08:44 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +        } else {
Отформатировать.

2022-12-20 08:46 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +        QString seriesDescription;
Переменная seriesDescription не используется.

2022-12-20 08:53 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +    if (m_RenderWindows[i]->isWindow3d()) {
Заменить m_RenderWindows[i] на m_RenderWindows.at(i), чтобы исключить создание нового окна. В случае однострочной конструкции и необъемного условия предпочтительно использовать следующие форматирование:
if (condition) continue;

2022-12-20 09:00 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +    auto currrentRenderWindow = m_RenderWindows[i];
Заменить m_RenderWindows[i] на m_RenderWindows.at(i) и аналогичные места.

2022-12-20 09:04 UTC, IliaF commented on Modules/QtWidgets/include/QmitkAnnotationOverlay.h
> +     mitk::DataNode::Pointer getTopLayerNode(mitk::DataStorage::SetOfObjects::ConstPointer nodes, QmitkRenderWindow* renderWindow);
Отформатировать.

2022-12-23 07:59 UTC, zapok commented
http://195.210.170.210:8000/Qt2/vlad/Viewer-win64-2022-12-22_overlay_set2.zip

2022-12-23 08:04 UTC, IliaF approved these changes

2022-12-23 08:36 UTC, sercxjo approved these changes

2022-12-23 10:04 UTC, merged