Webgl theme last
kometa-dev/MITK pull request #60
Opened 2023-01-31 10:49 UTC by zapok

Добавлены сине-зеленые цвета и стили как в webgl.
Изменены иконки. Изменен порядок кнопок. Доработан дата менеджер.

Задачи:
https://kometa-viewer.atlassian.net/browse/QTVIEW-183
https://kometa-viewer.atlassian.net/browse/QTVIEW-188
https://kometa-viewer.atlassian.net/browse/QTVIEW-190
https://kometa-viewer.atlassian.net/browse/QTVIEW-197
https://kometa-viewer.atlassian.net/browse/QTVIEW-203
https://kometa-viewer.atlassian.net/browse/QTVIEW-221
https://kometa-viewer.atlassian.net/browse/QTVIEW-220
https://kometa-viewer.atlassian.net/browse/QTVIEW-222
https://kometa-viewer.atlassian.net/browse/QTVIEW-223

Собирать с веткой вьювера webgl_theme

http://195.210.170.210:8000/vlad/Viewer-win64-2023-01-31_webgl_styles_last.zip

2023-03-06 08:24 UTC, zapok commented
http://195.210.170.210:8000/vlad/Viewer-win64-2023-03-04_measuments.zip

2023-03-16 11:35 UTC, IliaF requested changes

2023-03-16 11:35 UTC, IliaF commented on Plugins/org.mitk.gui.qt.datamanager/src/internal/QmitkDataManagerItemDelegate.cpp
> +  widget->setProperty("study", studyDescriptor);
Свойство "study" надо устанавливать только нод, которые описывают исследования:
if (studyDescriptor) {
   widget->setProperty("study", studyDescriptor);
}

2023-03-17 10:53 UTC, sercxjo requested changes
Сообщение коммита
[QTVIEW-220 merged](https://github.com/kometa-dev/MITK/pull/60/commits/f267ee533e9a18b39f4bf8cb47629f2a42237189) ни очём не говорит, и не все изменения коммита относятся к указанной задаче. Коммит был объединён.
Не нужно объединенять коммиты, если они относятся к разным задачам или вносят логически не связанные изменения.
Переделать коммит: разбить на части, описать суть изменений.

2023-03-17 12:55 UTC, zapok commented on Plugins/org.mitk.gui.qt.datamanager/src/internal/QmitkDataManagerItemDelegate.cpp
> +  widget->setProperty("study", studyDescriptor);
Изначально код верный.  Свойство "study" устанавливается либо в true либо в false

2023-03-17 15:21 UTC, sercxjo commented on Plugins/org.mitk.gui.qt.measurementtoolbox/resources/darkbluegreen/measurement.png
png переименовать svg, така как они на самом деле содержат svg

2023-03-17 17:51 UTC, zapok commented
> Сообщение коммита [QTVIEW-220 merged](https://github.com/kometa-dev/MITK/pull/60/commits/f267ee533e9a18b39f4bf8cb47629f2a42237189) ни очём не говорит, и не все изменения коммита относятся к указанной задаче. Коммит был объединён. Не нужно объединенять коммиты, если они относятся к разным задачам или вносят логически не связанные изменения. Переделать коммит: разбить на части, описать суть изменений.

Разделил коммиты.

2023-03-22 06:40 UTC, IliaF approved these changes

2023-03-22 21:59 UTC, sercxjo requested changes

2023-03-22 21:59 UTC, sercxjo commented on Plugins/org.mitk.gui.qt.datamanager/resources/darkbluegreen/Remove_48.png
svg

2023-03-22 21:59 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  std::vector<std::string> properties = { "levelwindow", "LookupTable", "visible", "selected", "volumerendering" };
static const

2023-03-22 21:59 UTC, sercxjo commented on Plugins/org.blueberry.ui.qt/resources/lightstyle.qss
> +  background-color: #bbbbbb;
взять цвет из палитры palette()

2023-03-22 21:59 UTC, sercxjo commented on Plugins/org.blueberry.ui.qt/resources/lightstyle.qss
> +  alternate-background-color: #d3d3d6;
взять цвет из палитры

2023-03-22 21:59 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkRenderWindowMenu.cpp
> +  */
Зачем в меню можно не показывать объёмную визуализацию, если в этом окне (3D) больше нечего показывать?

2023-03-22 21:59 UTC, sercxjo commented on Plugins/org.mitk.gui.qt.datamanager/src/QmitkDataManagerView.cpp
> +        //m_FilterModel->AddFilterPredicate(m_NodeWithNoDataFilterPredicate);
Добвить TODO: изменить предикат: не считать пустым узел с дочерними узлами

2023-03-24 07:56 UTC, IliaF commented on Modules/QtWidgets/src/QmitkRenderWindowMenu.cpp
> +  */
Меню будет переделываться, поэтому не вижу смысла в правке этого замечания.

2023-03-24 08:40 UTC, merged