Расположение виджетов для маммографии
kometa-dev/MITK pull request #62
Opened 2023-02-08 14:43 UTC by sercxjo

- Четыре окна по горизонтали в определённом порядке.
- Чтение и использование тэгов вида проекции для расположения в нужном окне.
- Поддержка маммографических серий с разными проекциями и автоматическое объединение одиночных снимков в такую серию.
- Поворот снимков к стандартной ориентации на экране, если есть вектора ориентации в тэгах.
- Поддержка серий томосинтеза.
- Прокрутка в пределах одного вида проекции.
QTVIEW-155

2023-02-27 12:59 UTC, IliaF requested changes

2023-02-27 12:59 UTC, IliaF commented on Modules/Core/src/Controllers/mitkCameraController.cpp
>        vtkCamera* camera = this->GetRenderer()->GetVtkRenderer()->GetActiveCamera();
Форматирование сделать.

2023-02-27 12:59 UTC, IliaF commented on Modules/Core/src/Controllers/mitkSliceNavigationController.cpp
> +      if (m_OrientationType == 1) viewDirection = Axial;
Привести к виду:
if () {
} else {
}

2023-02-27 12:59 UTC, IliaF commented on Modules/QtWidgets/include/QmitkStdMultiWidget.h
> +         LAYOUT_NULL = -1
Перенести в начало перечисления LAYOUT_NULL = -1, иначе при добавлении нового макета, забыв при этом указать значение, получим значение = 0. Учитывается при этом неименованное перечисление в QmitkRenderWindowMenu, который хранит также макеты?

2023-02-27 12:59 UTC, IliaF commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +    auto seachPredicate = [part=hangingPlan[i]](itk::MetaDataDictionary* dictionary){
Потерял "r":
searchPredicate

2023-02-27 12:59 UTC, IliaF commented on Modules/QtWidgets/include/QmitkStdMultiWidget.h
> +  void setMgSlicePos(unsigned int count=4);
Переименовать setMgSlicePos в setMammographySlicePos.

2023-02-27 12:59 UTC, IliaF commented on Modules/QtWidgets/include/QmitkStdMultiWidget.h
> +  void changeLayoutTo2DImagesUp(bool mg = false);
Переименовать mg в mammography, так как при беглом взгляде непонятно о чем идет речь.

2023-03-01 08:02 UTC, sercxjo commented
Добавил сброс масштаба при drag'n'drop, убрал смещение при масштабировании.

2023-03-12 08:36 UTC, merged