Added inverting color by inverting lookupTable
kometa-dev/MITK pull request #63
Opened 2023-04-05 13:05 UTC by zapok

Добавлена инвертация цвета для изображения при помощи инвертации lookupTable.
При таком подходе инвертацию цвета можно применить к изображению, к которому уже применена какая-то lookupTable.
Задача:
https://kometa-viewer.atlassian.net/browse/QTVIEW-174

2023-04-10 20:26 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  selectWidget(property(SELECTED_PROPERTY_NAME).toBool());
А зачем это делается?

2023-04-11 10:11 UTC, zapok commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  selectWidget(property(SELECTED_PROPERTY_NAME).toBool());
Если заменить на строчку 
if (property(SELECTED_PROPERTY_NAME).toBool()) selectWidget(true);
при перетаскивании из датаменеджеры превью с разными сериями в разные std  возникает ситуация когда свойство "selected" становится true, где это неверно (и инверсия цвета происходит не только для выделенного окна, а для нескольких). Поэтому надо оставить код
selectWidget(property(SELECTED_PROPERTY_NAME).toBool());
Для установке этого свойства в false для нод (и тогда уже всё правильно работает).

Константу выше заменил на SELECTED_PROPERTY_NAME

2023-07-13 09:53 UTC, IliaF requested changes

2023-07-13 09:53 UTC, IliaF commented on Modules/Core/src/Interactions/SynchronizationManager.cpp
> +  if (m_Levels.size()) {
Лучше использовать empty().

2023-07-13 09:53 UTC, IliaF commented on Modules/Core/src/Interactions/SynchronizationManager.cpp
> +        node->GetBoolProperty(invertPropName, invertValue, baseRenderer);
Переделать node->GetBoolProperty() на propertyList->GetBoolProperty() для исключения повторного получения списка свойств внутри node->GetBoolProperty().

2023-07-13 09:53 UTC, IliaF commented on Modules/Core/src/Rendering/mitkImageVtkMapper2D.cpp
> +  mitk::Point2D displayPoint;
Заполнить точку displayPoint.

2023-07-13 09:53 UTC, IliaF commented on Modules/QtWidgets/src/QmitkStdMultiWidget.cpp
> +  if (m_ActiveNode && m_MitkWidgetContainers.size()) {
!m_MitkWidgetContainers.empty()

2023-07-21 06:47 UTC, merged