Проблемы и баги по внешнему виду и оверлейному слою. Лого при старте.
kometa-dev/MITK pull request #66
Opened 2023-04-27 16:28 UTC by zapok

Исправлены разные проблемы и баги по внешнему виду и оверлейному слою.
Исправлена проблема с лого при старте.

Задачи:
https://kometa-viewer.atlassian.net/browse/QTVIEW-297
https://kometa-viewer.atlassian.net/browse/QTVIEW-324
https://kometa-viewer.atlassian.net/browse/QTVIEW-298
https://kometa-viewer.atlassian.net/browse/QTVIEW-325
https://kometa-viewer.atlassian.net/browse/QTVIEW-306
https://kometa-viewer.atlassian.net/browse/QTVIEW-338
https://kometa-viewer.atlassian.net/browse/QTVIEW-307

Сборка:
http://195.210.170.210:8000/vlad/Viewer-win64-2023-04-20_bugset1.zip

Связанный пулреквест:
https://github.com/kometa-dev/qt-viewer/pull/36

2023-06-22 12:46 UTC, IliaF commented on Modules/Core/src/Interactions/SynchronizationManager.cpp
> +      updateScale(baseRenderer, scale);
В случае, если sender не включен в синхронизацию, то scale установится во всех окнах, которые включены в синхронизацию, и sender?

2023-06-22 12:49 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +  SynchronizationManager::getInstance().updateCameraScale (baseRenderer, scale);
Пробел убрать.

2023-06-22 12:52 UTC, IliaF commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
> +    auto vtkRender = m_RulerVtkRenders[renderer];
Необходима проверка, что в QMap содержится элемент для целевого рендерера.

2023-06-26 14:58 UTC, zapok commented on Modules/Core/src/Interactions/SynchronizationManager.cpp
> +      updateScale(baseRenderer, scale);
Да. Пользователь делает обновление масштаба через активный оверлейный слой для изображения где этот активный элемент расположен, и скорее всего ожидает что что-то поменяется в любом случае.

2023-07-03 11:18 UTC, sercxjo commented on Modules/Core/src/Interactions/SynchronizationManager.cpp
> +      updateScale(baseRenderer, scale);
если окно выключено из синхронизации, я считаю неправильным синхронизировать с ним другие окна

2023-07-03 20:28 UTC, sercxjo requested changes

2023-07-03 20:28 UTC, sercxjo commented on Modules/QtWidgets/src/QmitkAnnotationOverlay.cpp
>      }
неправильный отступ

2023-07-04 17:04 UTC, zapok commented on Modules/Core/src/Interactions/SynchronizationManager.cpp
> +      updateScale(baseRenderer, scale);
Исправил

2023-07-07 09:58 UTC, IliaF approved these changes

2023-07-12 09:58 UTC, merged