Removed state machine from PointInteractor and PlanarFigureInteractor
kometa-dev/MITK pull request #9
Opened 2021-08-04 16:51 UTC by KuznetsovAlexander

https://kometa-viewer.atlassian.net/browse/QTVIEW-20

Убрал стейт-машину из двух дата-интеракторов.
Сделал отдельный базовый класс для тех интеракторов, которые все еще используют стейт-машину.

Ветка базируется на dcmtk-sorting.

2022-05-28 02:38 UTC, IliaF commented on Modules/Core/include/mitkDisplayInteractor.h
> +      Unkown = 0,
Unknown

2022-05-28 02:38 UTC, IliaF commented on Modules/Core/include/mitkDisplayInteractor.h
> +    Sign m_ThicklessSign = Sign::Unkown;
Unknown

2022-05-28 02:39 UTC, IliaF commented on Modules/Core/include/mitkDisplayInteractor.h
> +    Vector3D m_orthogonalVectorThickness;
m_orthogonalVectorThickness привести к локальному codestyle -> m_OrthogonalVectorThickness

2022-05-28 02:39 UTC, IliaF commented on Modules/Core/include/mitkDisplayInteractor.h
> +    double m_correctionFactorThickness;
m_correctionFactorThickness привести к локальному codestyle -> m_CorrectionFactorThickness

2022-05-28 03:34 UTC, IliaF commented on Modules/Segmentation/Interactions/mitkSmartBrushTool.cpp
> +//void mitk::SmartBrushTool::ConnectActionsAndFunctions()
Удалить закомментированный код

2022-05-28 03:56 UTC, IliaF requested changes

2022-05-28 03:56 UTC, IliaF commented on Modules/Segmentation/Interactions/mitkSmartBrushTool.cpp
> +//void mitk::SmartBrushTool::ConnectActionsAndFunctions()
Удалить закомментированный код.

2022-05-28 03:56 UTC, IliaF commented on Modules/Core/include/mitkDisplayInteractor.h
> +    Vector3D m_orthogonalVectorThickness;
m_orthogonalVectorThickness привести к локальному codestyle -> m_OrthogonalVectorThicknes

2022-05-28 03:56 UTC, IliaF commented on Modules/Core/include/mitkDisplayInteractor.h
> +    double m_correctionFactorThickness;
m_correctionFactorThickness привести к локальному codestyle -> m_CorrectionFactorThickness

2022-05-28 03:56 UTC, IliaF commented on Modules/Core/include/mitkDisplayInteractor.h
> +      Unkown = 0,
Unkown -> Unknown

2022-08-05 11:43 UTC, sercxjo approved these changes

2022-08-25 14:57 UTC, merged